# Using this as a placeholder for remembering the commands I need to type

activate:
	conda activate FERRET

extract_1981: 
	/fire8/jonc/Projects/smoke_planner_cansac_reanalysis_d03/extract/create_daylist.sh 1981
	python wrf_extract.py daylist_1981 main_CANSAC.jnl &> output_1981.log &


