# Using this as a placeholder for remembering the commands I need to type

activate:
	conda activate FERRET

run_1980:
	python wrf_extract.py daylist_1980_run1 hourlist main_CANSAC.jnl &> output_run1.log &
	python wrf_extract.py daylist_1980_run2 hourlist main_CANSAC.jnl &> output_run2.log &
	python wrf_extract.py daylist_1980_run3 hourlist main_CANSAC.jnl &> output_run3.log &
	python wrf_extract.py daylist_1980_run4 hourlist main_CANSAC.jnl &> output_run4.log &
	python wrf_extract.py daylist_1980_run5 hourlist main_CANSAC.jnl &> output_run5.log &
	python wrf_extract.py daylist_1980_run6 hourlist main_CANSAC.jnl &> output_run6.log &
	python wrf_extract.py daylist_1980_run7 hourlist main_CANSAC.jnl &> output_run7.log &
	python wrf_extract.py daylist_1980_run8 hourlist main_CANSAC.jnl &> output_run8.log &
	python wrf_extract.py daylist_1980_run9 hourlist main_CANSAC.jnl &> output_run9.log &
	python wrf_extract.py daylist_1980_run10 hourlist main_CANSAC.jnl &> output_run10.log &
	python wrf_extract.py daylist_1980_run11 hourlist main_CANSAC.jnl &> output_run11.log &
	python wrf_extract.py daylist_1980_run12 hourlist main_CANSAC.jnl &> output_run12.log &
	python wrf_extract.py daylist_1980_run13 hourlist main_CANSAC.jnl &> output_run13.log &
	python wrf_extract.py daylist_1980_run14 hourlist main_CANSAC.jnl &> output_run14.log &
	python wrf_extract.py daylist_1980_run15 hourlist main_CANSAC.jnl &> output_run15.log &
	python wrf_extract.py daylist_1980_run16 hourlist main_CANSAC.jnl &> output_run16.log &
	python wrf_extract.py daylist_1980_run17 hourlist main_CANSAC.jnl &> output_run17.log &
	python wrf_extract.py daylist_1980_run18 hourlist main_CANSAC.jnl &> output_run18.log &
	python wrf_extract.py daylist_1980_run19 hourlist main_CANSAC.jnl &> output_run19.log &
	python wrf_extract.py daylist_1980_run20 hourlist main_CANSAC.jnl &> output_run20.log &
	python wrf_extract.py daylist_1980_run21 hourlist main_CANSAC.jnl &> output_run21.log &
	python wrf_extract.py daylist_1980_run22 hourlist main_CANSAC.jnl &> output_run22.log &
	python wrf_extract.py daylist_1980_run23 hourlist main_CANSAC.jnl &> output_run23.log &
	python wrf_extract.py daylist_1980_run24 hourlist main_CANSAC.jnl &> output_run24.log &
	python wrf_extract.py daylist_1980_run25 hourlist main_CANSAC.jnl &> output_run25.log &
	python wrf_extract.py daylist_1980_run26 hourlist main_CANSAC.jnl &> output_run26.log &

