# Using this as a placeholder for remembering the commands I need to type

activate:
	conda activate FERRET

aggregate_1981: 
	python wrf_aggregate.py varlist yearlist monthlist &> output_1981.log &


